apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-28327  # Replace with your desired name if needed
  labels:
    app: nginx
spec:
  replicas: 2  # Two replicas for high availability
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.21  # Using the specified image
        ports:
        - containerPort: 80  # Default HTTP port
        resources:
          requests:
            memory: "16Mi"  # Minimum memory request
            cpu: "50m"       # Minimum CPU request (half a CPU)
          limits:
            memory: "128Mi"  # Maximum memory limit
            cpu: "100m"      # Maximum CPU limit (one CPU)
