apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-pvc-28327
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: slow  # Replace with your storage class name
