apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role
  namespace: vabvl9-helm  # Change to the desired namespace
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]  # Specifies Pods and Services resources
    verbs: ["get", "list", "watch"]  # Allows get, list, and watch actions
