apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nginx-role-28327
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nginx-rolebinding-28327
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nginx-role-28327
subjects:
- kind: ServiceAccount
  name: nginx-service-account
  namespace: <your-namespace>
