apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-route
  namespace:  vabvl9-helmapp
spec:
  to:
    kind: Service
    name: nginx-service
    weight: 100
  port:
    targetPort: 80
  tls:
    termination: edge
  wildcardPolicy: None
